
#include "InjectedData.h"
#include "Defines.h"

void InjectedData_Init(InjectedData* data, SYSTEMTIME const* t, DWORD_PTR baseAddr, char const* machine)
{
    char buf[256];

    SecureZeroMemory(&buf[0], sizeof(buf));
    wsprintfA(buf, "This file is generated by WSTC Sniffer %s %s developed by Shauren <shauren.trinity@gmail.com> for build %d, built %02hd/%02hd/%04hd %02hd:%02hd:%02hd (UTC).", machine, WSTC_VERSION_STRING, ClientBuild, t->wDay, t->wMonth, t->wYear, t->wHour, t->wMinute, t->wSecond);
    lstrcpyA(data->FileNameFormat, "%u_%04hu-%02hu-%02hu_%02hu-%02hu-%02hu.pkt");
    lstrcpyA(data->CreateFileFailedMsg, "Failed to create file: %s");
    lstrcpyA(data->FileHeader, buf);
    data->FileHeaderLength = (DWORD)lstrlenA(data->FileHeader);
    data->LockFlags = 0;
    data->SniffFile = INVALID_HANDLE_VALUE;
    data->Build = ClientBuild;
    data->WrittenSessionKey = FALSE;

    data->LocaleIndex = (DWORD*)(ClientLocaleIdxOffset + baseAddr);
    data->LocaleStrings = (char**)(ClientLocaleStrOffset + baseAddr);

    // CLIENT
    data->ConsolePrintf = (pConsolePrintf)(ConsolePrintf_Offset + baseAddr);
    data->Connection_ = (pConnection)(Connection_Offset + baseAddr);
    data->GetSessionKey_ = (pGetSessionKey)(GetSessionKey_Offset + baseAddr);
}
